version: "3.9"

services:
  devocional-web:
    image: devocional-quest-web:latest
    networks:
      - network_public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"

        - "traefik.http.routers.devocional-web.rule=Host(`relevanteen.aleftec.com.br`)"
        - "traefik.http.routers.devocional-web.entrypoints=websecure"
        - "traefik.http.routers.devocional-web.tls=true"
        - "traefik.http.routers.devocional-web.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.devocional-web.service=devocional-web"
        - "traefik.http.services.devocional-web.loadbalancer.server.port=80"


  devocional-api:
    image: devocional-quest-image:latest
    environment:
      NODE_ENV: production
      PORT: 3009

      DB_HOST: 62.72.63.137
      DB_PORT: 5432
      DB_NAME: plano_leitura_quest
      DB_USER: root
      DB_PASSWORD: kZ7oYab65fQITbyPPV6CLgrL5NIONpwZ
      DATABASE_URL: postgresql://root:kZ7oYab65fQITbyPPV6CLgrL5NIONpwZ@62.72.63.137:5432/plano_leitura_quest

      REDIS_DISABLED: "false"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # remova senha se não usa
      # REDIS_PASSWORD: ""

      JWT_SECRET: fed9f2b3618712f636d2a18dcdea9226b9c4ba090a6633f21de0c24230a6ded6
      EXPO_PUBLIC_API_URL: https://relevanteen.aleftec.com.br/api
      OAUTH_SERVER_URL: https://relevanteen.aleftec.com.br
      CORS_ORIGIN: https://relevanteen.aleftec.com.br
      APP_NAME: "Devocional Quest"
      APP_URL: https://relevanteen.aleftec.com.br

    networks:
      - network_public
      - internal

    # IMPORTANTÍSSIMO: produção = rodar só a API
    command: ["node", "dist/index.js"]
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"

        # API em /api
        - "traefik.http.routers.devocional-api.rule=Host(`relevanteen.aleftec.com.br`) && PathPrefix(`/api`)"
        - "traefik.http.routers.devocional-api.entrypoints=websecure"
        - "traefik.http.routers.devocional-api.tls=true"
        - "traefik.http.routers.devocional-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.devocional-api.priority=100"

        - "traefik.http.services.devocional-api.loadbalancer.server.port=3009"


  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - internal
    deploy:
      replicas: 1

networks:
  network_public:
    external: true
    name: network_public

  internal:
    driver: overlay
    attachable: true

volumes:
  redis_data:
